version: '3.8'

services:
  api1:
    image: lucasteles/rinha-de-backend
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - 8080
    environment:
      DB_HOST: db
      CACHE_HOST: redis:6379
      DOTNET_TieredPGO: 1
      DOTNET_ReadyToRun: 0
      DOTNET_TC_QuickJitForLoops: 1
    networks:
      - api-network
    ports:
      - '9001:8080'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    image: lucasteles/rinha-de-backend
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    expose:
      - 8080
    environment:
      DB_HOST: db
      CACHE_HOST: redis:6379
      DOTNET_TieredPGO: 1
      DOTNET_ReadyToRun: 0
      DOTNET_TC_QuickJitForLoops: 1
    networks:
      - api-network
    ports:
      - '9002:8080'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  db:
    image: postgres:latest
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB' -c 'synchronous_commit=off' -c 'fsync=off' -c 'full_page_writes=off'
    networks:
      - api-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pessoas_db
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.65'
          memory: '1.2GB'

  redis:
    image: redis
    networks:
      - api-network
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 20s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    networks:
      - api-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.3GB'

  gatling:
    image: gatling:local
    build:
      context: stress-test
      dockerfile: Dockerfile
    depends_on:
      - api1
      - api2
    networks:
      - api-network
    volumes:
      - ./stress-test:/opt/stress-test
    command:
      sh -c "/opt/stress-test/run-test.sh"


networks:
  api-network:
    driver: bridge
